export const projects = [
  {
    id: 1,
    title: 'AM Store',
    chips: ['ReactJs', 'TailwindCss', 'Formik', 'Yup', 'Firestore'],
    description: 'E-commerce made with ReactJs',
    deploy: 'https://amstore-ch.vercel.app',
    img: 'https://res.cloudinary.com/dv8nczwtj/image/upload/v1689116012/Google/imagen_2023-07-11_195327399_job7pw.png',
    github: 'https://github.com/a-Marino/E-Commerce-CoderHouse',
  },
  {
    id: 2,
    title: 'FilmsToWatch',
    chips: ['VueJs', 'TMDB API', 'TailwindCss'],
    description: 'Website to search info about movies and series',
    deploy: 'https://films-towatch.web.app',
    img: 'https://res.cloudinary.com/dv8nczwtj/image/upload/v1689826707/Google/imagen_2023-07-20_011821981_oumqme.png',
    github: 'https://github.com/a-Marino/filmsToWatch',
  },
  {
    id: 3,
    title: 'FlixTV',
    chips: ['ReactJs', 'TailwindCss', 'Framer Motion'],
    img: 'https://res.cloudinary.com/dv8nczwtj/image/upload/v1691779298/Google/imagen_2023-08-11_154135064_yniyd9.png',
    description: 'Streaming Service based in Behance design',
    deploy: 'https://streaming-service-fawn.vercel.app',
    github: 'https://github.com/a-Marino/streamingService',
  },
  {
    id: 4,
    title: 'gym System',
    chips: ['ReactJs', 'TailwindCss', 'Firebase', 'NodeJs'],
    img: 'https://res.cloudinary.com/dv8nczwtj/image/upload/v1724424521/Screenshot_2024-08-23_114601_jbve9q.png',
    description: 'Gym web with Classes, Plans, Account Managment, etc.',
    deploy: 'https://gym-sys.vercel.app/',
    github: 'https://github.com/a-Marino/gymSys',
  },
];
